/**
 * Core Global Skill Catalog Seed Dataset (Phase C6)
 * Normalized skill definitions for Frontend Developer, Backend Developer, Full Stack Developer, Data Analyst, Data Scientist, and foundational career paths.
 */
const skillsSeedData = [
  // Frontend & Core Web Skills
  {
    name: "HTML5",
    slug: "html5",
    category: "web",
    description: "Semantic HTML5 markup, document structure, accessibility elements, forms, and web APIs.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },
  {
    name: "CSS3 & Modern Layouts",
    slug: "css3",
    category: "web",
    description: "Styling web documents using CSS3, Flexbox, CSS Grid, Responsive Media Queries, and CSS Variables.",
    difficulty: "beginner",
    prerequisiteSlugs: ["html5"],
  },
  {
    name: "JavaScript (ES6+)",
    slug: "javascript",
    category: "programming",
    description: "Core JavaScript programming: syntax, DOM manipulation, async/await, ES Modules, and closure concepts.",
    difficulty: "beginner",
    prerequisiteSlugs: ["html5"],
  },
  {
    name: "Git & GitHub",
    slug: "git",
    category: "cloud_devops",
    description: "Version control fundamentals: git commits, branching, merging, pull requests, and GitHub workflows.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },
  {
    name: "Responsive Web Design",
    slug: "responsive-design",
    category: "web",
    description: "Designing websites for mobile, tablet, and desktop screens using fluid grids, media queries, and mobile-first principles.",
    difficulty: "beginner",
    prerequisiteSlugs: ["css3"],
  },
  {
    name: "RESTful APIs & Fetch/Axios",
    slug: "rest-api",
    category: "web",
    description: "Consuming HTTP endpoints, JSON data parsing, request headers, status codes, and asynchronous data fetching.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["javascript"],
  },
  {
    name: "TypeScript",
    slug: "typescript",
    category: "programming",
    description: "Typed JavaScript subset: static typing, interfaces, generics, type inference, and compiler configuration.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["javascript"],
  },
  {
    name: "React.js",
    slug: "react",
    category: "web",
    description: "Component-driven UI development: JSX, React Hooks (useState, useEffect, useMemo), props, and component lifecycle.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["javascript", "html5", "css3"],
  },
  {
    name: "State Management",
    slug: "state-management",
    category: "web",
    description: "Managing global frontend application state using Context API, Redux Toolkit, or Zustand.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["react"],
  },
  {
    name: "Web Accessibility (a11y)",
    slug: "web-accessibility",
    category: "web",
    description: "Building inclusive interfaces conforming to WCAG standards using ARIA attributes, keyboard navigation, and semantic tags.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["html5", "css3"],
  },
  {
    name: "Frontend Testing",
    slug: "unit-testing-frontend",
    category: "web",
    description: "Automated component and integration testing using Vitest, Jest, and React Testing Library.",
    difficulty: "advanced",
    prerequisiteSlugs: ["react", "typescript"],
  },
  {
    name: "Web Performance Optimization",
    slug: "web-performance",
    category: "web",
    description: "Optimizing Web Vitals: code splitting, lazy loading, asset compression, image optimization, and bundle analysis.",
    difficulty: "advanced",
    prerequisiteSlugs: ["react", "javascript"],
  },

  // Backend & Infrastructure Skills
  {
    name: "Node.js Runtime",
    slug: "node-js",
    category: "programming",
    description: "Server-side JavaScript execution: Node.js runtime, Event Loop, Non-blocking I/O, File System (fs), and CommonJS/ES Modules.",
    difficulty: "beginner",
    prerequisiteSlugs: ["javascript"],
  },
  {
    name: "Express.js Framework",
    slug: "express-js",
    category: "web",
    description: "Server-side web application framework: routing, middleware pipelines, request parsing, and error handling.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["node-js", "rest-api"],
  },
  {
    name: "SQL & Relational Databases",
    slug: "sql-relational-db",
    category: "data",
    description: "Relational database concepts: SELECT, INSERT, UPDATE, DELETE queries, JOINs, GROUP BY, aggregations, and normalization.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },
  {
    name: "PostgreSQL",
    slug: "postgresql",
    category: "data",
    description: "Advanced relational database management: schemas, indexes, foreign keys, transactions, JSONB, and connection pooling.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["sql-relational-db"],
  },
  {
    name: "MongoDB & NoSQL",
    slug: "mongodb-nosql",
    category: "data",
    description: "Document-oriented database engineering: BSON documents, collections, indexing, aggregation pipelines, and CRUD operations.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },
  {
    name: "Data Modeling & ORM/ODM",
    slug: "data-modeling",
    category: "data",
    description: "Designing database schemas, entity relationships, Mongoose ODMs, Prisma/Sequelize ORMs, and migration management.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["sql-relational-db", "mongodb-nosql"],
  },
  {
    name: "Backend Auth & API Security",
    slug: "backend-auth-security",
    category: "security",
    description: "Securing backend APIs: password hashing (bcrypt), JWT authentication, OAuth2, CORS, rate limiting, and OWASP Top 10 defenses.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["express-js", "rest-api"],
  },
  {
    name: "Backend Testing",
    slug: "unit-testing-backend",
    category: "programming",
    description: "Automated backend unit and API integration testing using Jest, Supertest, and test database fixtures.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["node-js", "express-js"],
  },
  {
    name: "Docker & Containerization",
    slug: "docker",
    category: "cloud_devops",
    description: "Packaging backend applications into lightweight containers: Dockerfiles, images, containers, and Docker Compose environments.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["linux-basics", "git"],
  },
  {
    name: "Linux CLI & Server Basics",
    slug: "linux-basics",
    category: "cloud_devops",
    description: "Navigating Linux terminals, file permissions, shell scripts, environment variables, system signals, and process management.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },

  // Data Analytics & Data Science Skills (Phase C6.3 Additions)
  {
    name: "Python Programming",
    slug: "python",
    category: "programming",
    description: "Master Python programming: data structures, control flow, functions, modules, virtual environments, and data processing libraries.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },
  {
    name: "Pandas & Data Manipulation",
    slug: "pandas",
    category: "data",
    description: "Manipulate, clean, aggregate, and analyze tabular datasets using Python's Pandas and NumPy ecosystem.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["python"],
  },
  {
    name: "Data Visualization & Dashboarding",
    slug: "data-visualization",
    category: "data",
    description: "Transform raw analytical findings into clear visual charts, executive dashboards, and data stories using tools like Matplotlib, Seaborn, and BI platforms.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },
  {
    name: "Excel & Spreadsheet Analytics",
    slug: "excel-spreadsheets",
    category: "data",
    description: "Master spreadsheet data analysis: formulas (VLOOKUP, XLOOKUP, INDEX/MATCH), Pivot Tables, conditional formatting, and chart reporting.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },

  // Data Science & AI/ML Skills (Phase C6.4 Additions)
  {
    name: "Machine Learning",
    slug: "machine-learning",
    category: "ai_ml",
    description: "Supervised and unsupervised machine learning algorithms: classification, regression, clustering, ensemble methods (Random Forest, XGBoost), and scikit-learn.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["python", "pandas"],
  },
  {
    name: "Deep Learning & Neural Networks",
    slug: "deep-learning",
    category: "ai_ml",
    description: "Deep neural networks, activation functions, backpropagation, CNNs, RNNs, LSTMs, Transformers, and PyTorch/TensorFlow frameworks.",
    difficulty: "advanced",
    prerequisiteSlugs: ["machine-learning"],
  },
  {
    name: "MLOps & Model Deployment",
    slug: "mlops",
    category: "cloud_devops",
    description: "Machine learning operations: model packaging, REST API serving, CI/CD pipelines, model monitoring, continuous training, and deployment.",
    difficulty: "advanced",
    prerequisiteSlugs: ["machine-learning", "docker"],
  },
  // UI/UX Design Skills (Phase C6.11 Additions)
  {
    name: "UI/UX Design Principles",
    slug: "design-principles",
    category: "design",
    description: "Fundamental visual and user experience design principles: visual hierarchy, typography, color theory, spacing, contrast, alignment, and Gestalt principles.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },
  {
    name: "User Research & Usability Testing",
    slug: "user-research",
    category: "design",
    description: "User research methodologies, interviewing techniques, user personas, journey mapping, usability testing, and qualitative/quantitative research synthesis.",
    difficulty: "beginner",
    prerequisiteSlugs: [],
  },
  {
    name: "Wireframing & Interactive Prototyping",
    slug: "wireframing-prototyping",
    category: "design",
    description: "Translating user requirements into low-fidelity wireframes, high-fidelity UI layouts, interactive component prototypes, and micro-interaction specifications.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["design-principles", "user-research"],
  },
  {
    name: "Design Systems & Component Libraries",
    slug: "design-systems",
    category: "design",
    description: "Architecting scalable UI design systems: design tokens, reusable component libraries, style guides, component states, and developer handoff specifications.",
    difficulty: "intermediate",
    prerequisiteSlugs: ["design-principles", "wireframing-prototyping"],
  },
];

module.exports = skillsSeedData;
